In [1]:
import pandas as pd
import numpy as np

In [2]:
maasSozlugu = {"isim": ["ali","veli","ayşe","fatma","mehmet"],
               "departman": ["yazılım","yazılım","pazarlama","pazarlama","insan kaynakları"],
               "maas": [5000, 6000, 4000, 4500, 3500]
               }

In [3]:
maasDateFrame = pd.DataFrame(maasSozlugu)

In [4]:
maasDateFrame

     isim         departman  maas
0     ali           yazılım  5000
1    veli           yazılım  6000
2    ayşe         pazarlama  4000
3   fatma         pazarlama  4500
4  mehmet  insan kaynakları  3500

In [7]:
maasDateFrame["departman"].unique()
maasDateFrame["departman"].nunique()
maasDateFrame["departman"].value_counts()

departman
yazılım             2
pazarlama           2
insan kaynakları    1
Name: count, dtype: int64

In [10]:
def bruttennet(maas):
    return maas * 0.66

In [11]:
maasDateFrame["maas"].apply(bruttennet)

0    3300.0
1    3960.0
2    2640.0
3    2970.0
4    2310.0
Name: maas, dtype: float64

In [12]:
maasDateFrame.isnull()

    isim  departman   maas
0  False      False  False
1  False      False  False
2  False      False  False
3  False      False  False
4  False      False  False

In [34]:
yeniBirVeri = {
    "karakter sınıfı": ["south park","south park", "simpsonz", "simpsonz","south park","south park"],"karakter ismi": ["cartman", "kyle", "stan","mart","apral","apral"],"karakter yaşı": [10, 9, 8, 7, 6,20]
                }
yeniDateFrame = pd.DataFrame(yeniBirVeri)

In [41]:
yeniDateFrame

  karakter sınıfı karakter ismi  karakter yaşı
0      south park       cartman             10
1      south park          kyle              9
2        simpsonz          stan              8
3        simpsonz          mart              7
4      south park         apral              6
5      south park         apral             20

In [49]:
yeniDateFrame.pivot_table(values="karakter yaşı", index=["karakter sınıfı", "karakter ismi"], aggfunc="mean")

                               karakter yaşı
karakter sınıfı karakter ismi
simpsonz        mart                     7.0
                stan                     8.0
south park      apral                   13.0
                cartman                 10.0
                kyle                     9.0